[project]
name = "llm-heuristics"
version = "0.1.1"
description = "Using LLMs to learn heuristics for classical planning"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "google-genai>=1.11.0",
    "lab>=8.4",
    "openai>=1.61.1",
    "pandas>=2.2.3"
]

[project.optional-dependencies]
cu128 = [
    "torch==2.9.1",
    "vllm",
]
cu130 = [
    "torch==2.9.1",
    "vllm",
]

[tool.uv]
conflicts = [
    [
        {extra = "cu128"},
        {extra = "cu130"},
    ]
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = [
    {index = "torch-cu128", extra = "cu128"},
    {index = "torch-cu130", extra = "cu130"},
]

[[tool.uv.index]]
name = "torch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "torch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true